### PR TITLE
Include updated Grafana dashboard examples

### PR DESCRIPTION
**Pull request by mitchtech**
The referenced Grafana dashboards from https://grafana.com/grafana/dashboards?search=unifi-poller use multiple deprecated panels. This pull request includes all 12 in the repo for version control. The 6 prometheus dashboards have been updated with the latest standard configs and panels. 

Changes:
- Singlestat Gauge visualizations updated to latest standalone Gauge visualizations. Singlestat was deprecated in Grafana 7.0 and removed in Grafana 8.0: https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/stat/
- Legacy Table (old) panels to Table panels. The Table (old) panel uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana: https://grafana.com/docs/grafana/latest/developers/angular_deprecation/
- Legacy Graph panels to Time Series panels. The Graph (old) panel uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana: https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

### CODE REVIEW

**Comment by platinummonkey** [comment]
👋 this is great can you do this against the unpoller/dashboards repository? 🙏

**Comment by jlpedrosa** [comment]
+1 to @platinummonkey, also the helm chart automatically installs the Dashboards from grafana.com, so adding them in the right repo will make everyone get it automatically updated for the ones using k8s/helm.

**Comment by mitchtech** [comment]
Ah, the dashboards are in separate repo, that explains why I couldn't find them here! 

PR for Prometheus versions updated there also: 
https://github.com/unpoller/dashboards/pull/38

**Comment by mitchtech** [comment]
Closing as this was merged in the dashboards repo here: https://github.com/unpoller/dashboards/pull/38

**Pull request closed without merging**
